spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job-business?useUnicode=true&characterEncoding=UTF-8
    username: wangzhi
    password: 123456
#ָmapper.xml 所在的位置
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml
#打印输出sql语句
  logging:
      level:
        com:
          job:
            dao: debug
  file: D:/job/job-springboot.log
server:
  port: 10010
# job 相关配置
job:
  executor:
    appname: job-springboot
    ip:
    port: 10020
    logpath: D:/auto-job/jobhandler
    logretentiondays: -1
### auto-job admin address list, such as "http://address" or "http://address01,http://address02"
  admin:
    addresses: http://127.0.0.1:9090/auto-job-admin
  accessToken:

